insert into item (item_internal_name, item_display_name, item_cost, image, for_sale, usage, ignore_stealth, covert, turn_cost, target_damage, turn_change, self_use, plural) values 
('charcoal', 'Charcoal', 10, default, false, 'Purges Poisons, Burns Merrily', true, true, default, 20, default, true, null),
('sake', 'Sake', 30, default, false, 'Warms the Soul', true, true, default, 1, default, true, null),
('mirror', 'Mirror Shard', 120, default, false, 'Reflects Light', true, true, default, 5, default, true, null),
('shell', 'Shell Fragment', 700, default, false, 'Insulates against Flame', true, true, default, 0, default, true, null),
('prayerwheel', 'Prayer Wheel', 150, default, false, 'Lifts Curses', true, true, default, 0, default, true, null),
('lantern', 'Hooded Lantern', 50, default, false, 'A lantern for light and flame', true, true, default, 20, default, true, null),
('sushi', 'Sushi', 50, default, false, 'For immediate consumption', true, true, default, 20, default, true, null),
('fugu', 'Fugu Blowfish', 50, default, false, 'Delicious, or Deadly', true, true, default, 20, default, true, null),

('oyoroi', 'O-yoroi Great Armor', 3000, default, false, 'Woven Armor with a Metal Breastplate against piercing and slashing', true, true, default, 3000, default, true, 's'),
('kozando', 'Kozan-do Scale Armor', 1600, default, false, 'Scale Plated Armor against slashing', true, true, default, 0, default, true, 's'),
('domaru', 'Do-Maru Woven Armor', 1000, default, false, 'Woven Armor against piercing and slashing', true, true, default, 0, default, true, 's'),
('tanko', 'Tanko Scale Armor', 900, default, false, 'Lamellate Armor against Crushing Blows', true, true, default, 0, default, true, 's'),
('tatamido', 'Tatami-do Folding Armor', 1500, default, false, 'Laced Squares of Flexible Leather for easy movement', true, true, default, 0, default, true, 's'),
('keikogi', 'Keiko-Gi Suit', 70, default, false, 'Thick Cloth Uniform for unfettered movement', true, true, default, 0, default, true, 's'),
('kimono', 'Kimono', 170, default, true, 'Light Silk Clothing for formal wear', true, true, default, 0, default, true, 's'),
('hakama', 'Hakama Garb', 30, default, false, 'Pleated, Loose Pants and Shirt for unfettered movement', true, true, default, 0, default, true, 's'),
('mask', 'Menpo Mask', 600, default, false, 'For Disguise or Intimidation', true, true, default, 0, default, true, 's'),

('katana', 'Katana', 1800, default, true, 'Crafted Sword for Slashing', false, false, default, 1800, default, true, null),
('meito', 'Meito Named Katana', 3000, default, false, 'Folded-Steel Named Sword for Slashing', true, false, default, 3000, default, true, null),
('naginata', 'Naginata Spear', 750, default, false, 'Long Reached, Curved Spear for Piercing and Slashing', false, false, default, 750, default, true, 's'),
('kunai', 'Kunai', 50, default, true, 'For Digging and Planting', true, true, default, 100, default, true, null),
('kusarigama', 'Kusarigama Chain Sickle', 500, default, false, 'For Swinging Slashes and Entanglement', true, false, default, 500, default, true, 's'),
('kama', 'Kama Sickle', 55, default, true, 'For Reaping Rice', false, false, default, 55, default, true, null),
('tetsubo', 'Tetsubo Club', 140, default, false, 'For Piercing, Crushing Blows', false, false, default, 140, default, true, null),
('nunchaku', 'Nunchaku', 180, default, false, 'Thrashing Blows with a long reach', true, false, default, 180, default, true, null),
('zanbato', 'Zanbato Long Sword', 660, default, false, 'For Heavy Slashing Blows with a long reach', true, false, default, 660, default, true, null),
('eku', 'Eku Wooden Oar', 30, default, false, 'For Slow, Wide-Arcing Blows', true, false, default, 130, default, true, 's'),
('ono', 'Ono Axe', 10, default, false, 'Great for Beheadings and De-limbing', false, false, default, 110, default, true, 's'),
('nekote', 'Neko-Te Claws', 450, default, false, 'For Poisoned slashing or climbing', false, true, default, 30, default, true, null),
('hamagari', 'Hamagari Saw', 77, default, true, 'For Poisoned slashing or climbing', false, true, default, 177, default, true, 's'),
('bo', 'Bo Staff', 70, default, true, 'For Ease of Walking', true, true, default, 170, default, true, 's'),
('tessen', 'Tessen Fan', 150, default, true, 'For Cooling Air', false, true, default, 80, default, true, 's');
