watch:
  directories:
    - deploy/tests
    - deploy
    - deploy/templates
    - deploy/lib/control
    - deploy/lib/data
    - deploy/www
    - deploy/model
  fileMask: '*.php'
notifications:
  passingTests: false
phpunit:
  binaryPath: vendor/bin/phpunit