language: php

env:
  - INSTALL=full_install

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true

before_install:

    - chmod ug+rx ./configure
    - chmod ug+rx scripts/travis/*
    #- git submodule init
    #- git submodule update

install:
    - echo -e "CC_DIR=./cc/\nDBNAME=nw\nCOMPOSER=composer\nDBUSER=ninjamaster\nDBCREATINGUSER=ninjamaster" > CONFIG
    - ./configure
    - make ci
    - readlink -f deploy/resources.php
    - cat deploy/resources.php

after_install:
    - php -v
    - echo "Getting the title from nw.local if possible"
    - wget -qO- 'nw.local' | perl -l -0777 -ne 'print $1 if /<title.*?>\s*(.*?)\s*<\/title/si'
    - echo "Getting full html from http://nw.local if possible"
    - curl http://nw.local


script: make ci-test

#Just to limit noise in the test area, this is separated
after_script:

after_failure: ls && composer --version && vendor/bin/phpunit --version && php --version
after_success: 
