language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

matrix:
  allow_failures:
    - php: 5.4

before_script:
    - pear channel-discover pear-smarty.googlecode.com/svn
    - pear install smarty/smarty
    - phpenv rehash
    - composer install
    - psql -c 'create database nw;' -U postgres
    - sed 's/smarty/Smarty/' docs/tchalvakSAMPLEresources.php > deploy/resources.php
    - cp build.properties.tpl build.properties
    - cp buildtime.xml.tpl buildtime.xml
    - cp connection.xml.tpl connection.xml
    - vendor/bin/propel-gen
    - vendor/bin/propel-gen insert-sql

script: vendor/bin/phpunit