language: php

env:
  - INSTALL=full_install
  - INSTALL=integration_install

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

before_install:
    - chmod ug+rx scripts/build/*.sh
    - chmod ug+rx scripts/travis/*
    - git submodule init
    - git submodule update

install:
    - ./scripts/travis/$INSTALL


before_script:
    - php -v
    - apache2ctl -S

script: ./scripts/travis/test

after_failure: ls && composer --version && vendor/bin/phpunit --version && php --version && apache2ctl --version && apache2ctl -S && tail -10 /var/log/apache2/error.log
