language: php

env:
  - INSTALL=full_install
  - INSTALL=integration_install

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.3.3 # Travis-ci doesn't support openssl in php 5.3.3
    - php: 5.5

before_script:
    - chmod ug+rx scripts/build/*.sh
    - chmod ug+rx scripts/travis/*
    - ./scripts/travis/$INSTALL
    - php -v

script: ./scripts/travis/test

after_failure: ls && composer --version && vendor/bin/phpunit --version && php --version && apache2 --version"
