language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.4
    - php: 5.5

before_script:
    - pear channel-discover pear-smarty.googlecode.com/svn
    - pear install smarty/smarty
    - phpenv rehash
    - ls /home/travis/.phpenv/versions/5.3.3/pear
    - ls /home/travis/.phpenv/versions/5.3.3/share/pyrus/.pear/php
    - composer install
    - psql -c 'create database nw;' -U postgres
    - cp docs/tchalvakSAMPLEresources.php deploy/resources.php
    - cp build.properties.tpl build.properties
    - cp buildtime.xml.tpl buildtime.xml
    - cp connection.xml.tpl connection.xml
    - vendor/bin/propel-gen
    - vendor/bin/propel-gen insert-sql

script: vendor/bin/phpunit