language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

matrix:
  allow_failures:
    - php: 5.4

before_script:
    - sudo bash scripts/travis/install
    - phpenv rehash
    - ls /usr/share/php5
    - ls /usr/share/php

script: vendor/bin/phpunit