language: php

env:
  - INSTALL=full_install
  - INSTALL=integration_install

php:
  - 5.3.3
  - 5.3
  - 5.4

matrix:
  allow_failures:
    - php: 5.4

before_script:
    - sudo bash scripts/travis/$INSTALL

script: vendor/bin/phpunit