nodeLinker: node-modules

enableTelemetry: false

logFilters:
  - code: YN0076
    level: discard

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
      spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.1.1.cjs
