#!/bin/bash
set -e
# Should set to exit on all errors
cd /home/tchalvak/nw/
git checkout dev
git fetch
git rebase origin/dev
filename=nw-`date '+%Y-%m-%d-Time-%H-%M'`.tar
echo $filename
git archive --format=tar HEAD:deploy/ > /home/ninjawars/${filename}
/home/ninjawars/deploy --clean -c=/home/ninjawars/test.conf /home/ninjawars/${filename}
