update players set uname = (substring(uname, 1, 1) || player_id) where uname != 'test';
update clan set clan_name = (substring(clan_name, 1, 1) || clan_id);
update players set pname = 'password';
update players set email = player_id || 'example@example.com';
update players set ip = '127.0.0.33';
update players set gold=(player_id/2), kills=(player_id/100);
update inventory set amount=10 where amount != 0 and amount != 1;
update past_stats set stat_result='no-one' where stat_type='Yesterday''s Vicious Killer';
truncate chat;
truncate events;
truncate messages;
truncate settings;
truncate ppl_online;
truncate dueling_log;
truncate levelling_log;
truncate players_backup;
truncate players_flagged;
