#!/bin/bash

destinationDB="ninjawarsMaster"
sourceHost="ninjawars.net"

if [[ $1 == "live" || $1 == "" ]]
then
	sourceDB="ninjawarsLive"
elif [[ $1 == "test" ]]
then
	sourceDB="ninjawarstest"
fi


echo -n "Warning: This will wipe your local $destinationDB database! Do you wish to continue? [y/N]"
read answer
if [[ $answer == "y" || $answer == "Y" ]]
then
	dropdb $destinationDB
	createdb -T template0 $destinationDB 
	ssh $sourceHost pg_dump $sourceDB | sudo -u postgres psql $destinationDB
	echo "Successfully mirrored $sourceDB!"
else
	echo "Aborted. No changes have been made."
	exit
fi
