#!/bin/bash

vendor/bin/propel-gen convert-conf #convert config file to array dump for improved performance
vendor/bin/propel-gen . diff migrate
vendor/bin/propel-gen . diff migrate
vendor/bin/propel-gen om

vendor/bin/phpunit