#!/bin/bash

# Include functions
_TRAVIS_DIR_="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
_DIR_=`echo $_TRAVIS_DIR_ | sed 's,scripts/travis,scripts/build,'`
source $_DIR_/functions.sh

# Main install scripts!
bash $_DIR_/install.sh postgres

# Debug
say_info "Display the virtualhost config" "DEBUG"
cat /etc/apache2/sites-availabe/nw.local