#!/bin/sh

# Include functions
_TRAVIS_DIR_=`dirname $0`
_DIR_=`echo $_TRAVIS_DIR_ | sed 's/travis/build/'`
source $_DIR_/functions.sh

# Main install scripts!
bash $_DIR_/install.sh postgres

# Pre-configured
export DISPLAY=:99.0
sh -e /etc/init.d/xvfb start