#!/bin/sh

# Include functions
_TRAVIS_DIR_=`dirname $0`
_DIR_=`echo $_TRAVIS_DIR_ | sed 's/travis/build/'`
source $_DIR_/functions.sh

# Main install scripts!
bash $_DIR_/install.sh postgres

# Setup web-config
set_web_default
bash $_DIR_/selenium.sh start