#!/bin/bash
# This script is used to prepare and run the test
#
# Run it :
# bash scripts/build/test.sh

# Include functions
_TRAVIS_DIR_=`dirname $0`
_DIR_=`echo $_TRAVIS_DIR_ | sed 's/travis/build/'`
source $_DIR_/functions.sh

say_loud "Preparing..." "TEST"

# Pre-configured
say_info "Export display and run xvfb" "DEBUG"
export DISPLAY=:99.0
sh -e /etc/init.d/xvfb start

bash $_DIR_/selenium.sh stop

java -jar /usr/lib/selenium/selenium-server-standalone-2.21.0.jar > /var/log/selenium/selenium-output.log 2> /var/log/selenium/selenium-error.log & echo $! > /tmp/selenium.pid

# Idle
say_loud "Waiting... [20 seconds]" "TEST"
sleep 5 
say_loud "Waiting... [15 seconds]" "TEST"
sleep 5 
say_loud "Waiting... [10 seconds]" "TEST"
sleep 5 
say_loud "Waiting... [5 seconds]" "TEST"
sleep 5 
ps aux | grep "selenium-server"

# Run
say_info "Assuming finished." "TEST"
say_loud "Running test-suite" "TEST"
vendor/bin/phpunit

# Analyze
say_loud "Display selenium logs." "TEST"
cat /var/log/selenium/selenium-output.log
cat /var/log/selenium/selenium-error.log

say_ok "Done." "TEST"