name: Chrome

on: push

jobs:
  chrome:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Chrome
        uses: cypress-io/github-action@v6
        timeout-minutes: 5
        with:
          build: npm run build
          start: npm start
          # wait-on: http://localhost:3000
          browser: chrome
